apiVersion: v1
kind: Namespace
metadata:
  name: citrix
  labels:
    name: citrix
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: citrix-node-controller
rules:
  - apiGroups: ["*"]
    resources: ["nodes", "configmaps", "pods", "namespaces", "serviceaccounts", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]

  - apiGroups: [""]
    resources: ["nodes", "configmaps", "pods", "namespaces", "serviceaccounts", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: citrix-node-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix-node-controller
subjects:
- kind: ServiceAccount
  name: citrix-node-controller
  namespace: citrix
apiVersion: rbac.authorization.k8s.io/v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: citrix-node-controller
  namespace: citrix
---
apiVersion: v1
kind: Service
metadata:
  name: citrix-node-controller
  namespace: citrix
  labels:
    app: citrix-node-controller
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: citrix-node-controller
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: citrix-node-controller
  namespace: citrix
spec:
  selector:
    matchLabels:
      app: citrix-node-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: citrix-node-controller
    spec:
      serviceAccountName: citrix-node-controller
      containers:
      - name: citrix-node-controller
        image: "quay.io/citrix/citrix-k8s-node-controller:beta-v3"
        imagePullPolicy: Always
        env:
        - name: NS_IP
          value: "xxxxxxx"
        - name: NS_USER
          valueFrom:
            secretKeyRef:
             name: nslogin
             key: username
        - name: NS_PASSWORD
          valueFrom:
            secretKeyRef:
             name: nslogin
             key: password
        - name: NETWORK
          value: "192.168.1.0/24"
        - name: REMOTE_VTEPIP
          value: "10.102.33.209"
        - name: VXLAN_PORT
          value: "8472"
        - name: VNID
          value: "200"
